repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/azjezz/pre-commit-php
    rev: v0.14.2
    hooks:
      - id: phpcs
      - id: phpstan
      - id: phpunit